# Main settings includes
include	make/settings.mk

# Individual project settings (Optional)
#BOOT		= new
#APP		= 1
#SPI_SPEED	= 40
SPI_MODE	= DOUT
#SPI_SIZE_MAP	= 2
ESPPORT		= COM3
ESPBAUD		= 256000

# Basic project settings
MODULES	= core modules modules/mqtt modules/drivers
LIBS	= c gcc hal phy pp net80211 lwip wpa crypto main ssl

# Root includes
include	make/common_nonos.mk